//Generated by DataSourceBaseGenerator

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Text;
using CommerceBuilder.Common;
using CommerceBuilder.Data;
using CommerceBuilder.Utility;

namespace CommerceBuilder.Marketing
{
    /// <summary>
    /// DataSource class for EmailListSignup objects
    /// </summary>
    public partial class EmailListSignupDataSource
    {
        /// <summary>
        /// Deletes a EmailListSignup object from the database
        /// </summary>
        /// <param name="emailListSignup">The EmailListSignup object to delete</param>
        /// <returns><b>true</b> if delete operation is successful, <b>false</b> otherwise</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Delete)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static bool Delete(EmailListSignup emailListSignup)
        {
            return emailListSignup.Delete();
        }

        /// <summary>
        /// Deletes a EmailListSignup object with given id from the database
        /// </summary>
        /// <param name="emailListSignupId">Value of EmailListSignupId of the object to delete.</param>
        /// <returns><b>true</b> if delete operation is successful, <b>false</b> otherwise</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Delete)]
        public static bool Delete(Int32 emailListSignupId)
        {
            EmailListSignup emailListSignup = new EmailListSignup();
            if (emailListSignup.Load(emailListSignupId)) return emailListSignup.Delete();
            return false;
        }

        /// <summary>
        /// Inserts/Saves a EmailListSignup object to the database.
        /// </summary>
        /// <param name="emailListSignup">The EmailListSignup object to insert</param>
        /// <returns><b>SaveResult</b> enumeration that represents the result of the save operation.</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Insert)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static SaveResult Insert(EmailListSignup emailListSignup) { return emailListSignup.Save(); }

        /// <summary>
        /// Loads a EmailListSignup object for given Id from the database.
        /// </summary>
        /// <param name="emailListSignupId">Value of EmailListSignupId of the object to load.</param>
        /// <returns>If the load is successful the newly loaded EmailListSignup object is returned. If load fails null is returned.</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static EmailListSignup Load(Int32 emailListSignupId)
        {
            return EmailListSignupDataSource.Load(emailListSignupId, true);
        }

        /// <summary>
        /// Loads a EmailListSignup object for given Id from the database.
        /// </summary>
        /// <param name="emailListSignupId">Value of EmailListSignupId of the object to load.</param>
        /// <param name="useCache">If true tries to load object from cache first.</param>
        /// <returns>If the load is successful the newly loaded EmailListSignup object is returned. If load fails null is returned.</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static EmailListSignup Load(Int32 emailListSignupId, bool useCache)
        {
            if (emailListSignupId == 0) return null;
            EmailListSignup emailListSignup = null;
            string key = "EmailListSignup_" + emailListSignupId.ToString();
            if (useCache)
            {
                emailListSignup = ContextCache.GetObject(key) as EmailListSignup;
                if (emailListSignup != null) return emailListSignup;
            }
            emailListSignup = new EmailListSignup();
            if (emailListSignup.Load(emailListSignupId))
            {
                if (useCache) ContextCache.SetObject(key, emailListSignup);
                return emailListSignup;
            }
            return null;
        }

        /// <summary>
        /// Counts the number of EmailListSignup objects in result if retrieved using the given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the EmailListSignup objects that should be loaded.</param>
        /// <returns>The number of EmailListSignup objects matching the criteria</returns>
        public static int CountForCriteria(string sqlCriteria)
        {
            Database database = Token.Instance.Database;
            string whereClause = string.IsNullOrEmpty(sqlCriteria) ? string.Empty : " WHERE " + sqlCriteria;
            DbCommand selectCommand = database.GetSqlStringCommand("SELECT COUNT(*) AS TotalRecords FROM ac_EmailListSignups" + whereClause);
            return CommerceBuilder.Utility.AlwaysConvert.ToInt(database.ExecuteScalar(selectCommand));
        }

        /// <summary>
        /// Loads a collection of EmailListSignup objects from the database based on given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the objects that should be loaded.</param>
        /// <returns>A collection of EmailListSignup objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static EmailListSignupCollection LoadForCriteria(string sqlCriteria)
        {
            return LoadForCriteria(sqlCriteria, 0, 0, string.Empty);
        }

        /// <summary>
        /// Loads a collection of EmailListSignup objects from the database based on given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the objects that should be loaded.</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of EmailListSignup objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static EmailListSignupCollection LoadForCriteria(string sqlCriteria, string sortExpression)
        {
            return LoadForCriteria(sqlCriteria, 0, 0, sortExpression);
        }

        /// <summary>
        /// Loads a collection of EmailListSignup objects from the database based on given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the objects that should be loaded.</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <returns>A collection of EmailListSignup objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static EmailListSignupCollection LoadForCriteria(string sqlCriteria, int maximumRows, int startRowIndex)
        {
            return LoadForCriteria(sqlCriteria, maximumRows, startRowIndex, string.Empty);
        }

        /// <summary>
        /// Loads a collection of EmailListSignup objects from the database based on given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the objects that should be loaded.</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of EmailListSignup objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static EmailListSignupCollection  LoadForCriteria(string sqlCriteria, int maximumRows, int startRowIndex, string sortExpression)
        {
            //CREATE THE DYNAMIC SQL TO LOAD OBJECT
            StringBuilder selectQuery = new StringBuilder();
            selectQuery.Append("SELECT");
            if (maximumRows > 0) selectQuery.Append(" TOP " + (startRowIndex + maximumRows).ToString());
            selectQuery.Append(" " + EmailListSignup.GetColumnNames(string.Empty));
            selectQuery.Append(" FROM ac_EmailListSignups");
            string whereClause = string.IsNullOrEmpty(sqlCriteria) ? string.Empty : " WHERE " + sqlCriteria;
            selectQuery.Append(whereClause);
            if (!string.IsNullOrEmpty(sortExpression)) selectQuery.Append(" ORDER BY " + sortExpression);
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand(selectQuery.ToString());
            //EXECUTE THE COMMAND
            EmailListSignupCollection results = new EmailListSignupCollection();
            int thisIndex = 0;
            int rowCount = 0;
            using (IDataReader dr = database.ExecuteReader(selectCommand))
            {
                while (dr.Read() && ((maximumRows < 1) || (rowCount < maximumRows)))
                {
                    if (thisIndex >= startRowIndex)
                    {
                        EmailListSignup emailListSignup = new EmailListSignup();
                        EmailListSignup.LoadDataReader(emailListSignup, dr);
                        results.Add(emailListSignup);
                        rowCount++;
                    }
                    thisIndex++;
                }
                dr.Close();
            }
            return results;
        }

        /// <summary>
        /// Counts the number of EmailListSignup objects for the given EmailListId in the database.
        /// <param name="emailListId">The given EmailListId</param>
        /// </summary>
        /// <returns>The Number of EmailListSignup objects for the given EmailListId in the database.</returns>
        public static int CountForEmailList(Int32 emailListId)
        {
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand("SELECT COUNT(*) AS TotalRecords FROM ac_EmailListSignups WHERE EmailListId = @emailListId");
            database.AddInParameter(selectCommand, "@emailListId", System.Data.DbType.Int32, emailListId);
            return CommerceBuilder.Utility.AlwaysConvert.ToInt(database.ExecuteScalar(selectCommand));
        }

        /// <summary>
        /// Loads a collection of EmailListSignup objects for the given EmailListId from the database
        /// </summary>
        /// <param name="emailListId">The given EmailListId</param>
        /// <returns>A collection of EmailListSignup objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static EmailListSignupCollection LoadForEmailList(Int32 emailListId)
        {
            return LoadForEmailList(emailListId, 0, 0, string.Empty);
        }

        /// <summary>
        /// Loads a collection of EmailListSignup objects for the given EmailListId from the database
        /// </summary>
        /// <param name="emailListId">The given EmailListId</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of EmailListSignup objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static EmailListSignupCollection LoadForEmailList(Int32 emailListId, string sortExpression)
        {
            return LoadForEmailList(emailListId, 0, 0, sortExpression);
        }

        /// <summary>
        /// Loads a collection of EmailListSignup objects for the given EmailListId from the database
        /// </summary>
        /// <param name="emailListId">The given EmailListId</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <returns>A collection of EmailListSignup objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static EmailListSignupCollection LoadForEmailList(Int32 emailListId, int maximumRows, int startRowIndex)
        {
            return LoadForEmailList(emailListId, maximumRows, startRowIndex, string.Empty);
        }

        /// <summary>
        /// Loads a collection of EmailListSignup objects for the given EmailListId from the database
        /// </summary>
        /// <param name="emailListId">The given EmailListId</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of EmailListSignup objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static EmailListSignupCollection LoadForEmailList(Int32 emailListId, int maximumRows, int startRowIndex, string sortExpression)
        {
            //CREATE THE DYNAMIC SQL TO LOAD OBJECT
            StringBuilder selectQuery = new StringBuilder();
            selectQuery.Append("SELECT");
            if (maximumRows > 0) selectQuery.Append(" TOP " + (startRowIndex + maximumRows).ToString());
            selectQuery.Append(" " + EmailListSignup.GetColumnNames(string.Empty));
            selectQuery.Append(" FROM ac_EmailListSignups");
            selectQuery.Append(" WHERE EmailListId = @emailListId");
            if (!string.IsNullOrEmpty(sortExpression)) selectQuery.Append(" ORDER BY " + sortExpression);
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand(selectQuery.ToString());
            database.AddInParameter(selectCommand, "@emailListId", System.Data.DbType.Int32, emailListId);
            //EXECUTE THE COMMAND
            EmailListSignupCollection results = new EmailListSignupCollection();
            int thisIndex = 0;
            int rowCount = 0;
            using (IDataReader dr = database.ExecuteReader(selectCommand))
            {
                while (dr.Read() && ((maximumRows < 1) || (rowCount < maximumRows)))
                {
                    if (thisIndex >= startRowIndex)
                    {
                        EmailListSignup emailListSignup = new EmailListSignup();
                        EmailListSignup.LoadDataReader(emailListSignup, dr);
                        results.Add(emailListSignup);
                        rowCount++;
                    }
                    thisIndex++;
                }
                dr.Close();
            }
            return results;
        }

        /// <summary>
        /// Updates/Saves the given EmailListSignup object to the database.
        /// </summary>
        /// <param name="emailListSignup">The EmailListSignup object to update/save to database.</param>
        /// <returns><b>SaveResult</b> enumeration that represents the result of the save operation.</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Update)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static SaveResult Update(EmailListSignup emailListSignup) { return emailListSignup.Save(); }

    }
}
