//Generated by DataSourceBaseGenerator

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Text;
using CommerceBuilder.Common;
using CommerceBuilder.Data;
using CommerceBuilder.Utility;

namespace CommerceBuilder.Payments
{
    /// <summary>
    /// DataSource class for GiftCertificate objects
    /// </summary>
    public partial class GiftCertificateDataSource
    {
        /// <summary>
        /// Deletes a GiftCertificate object from the database
        /// </summary>
        /// <param name="giftCertificate">The GiftCertificate object to delete</param>
        /// <returns><b>true</b> if delete operation is successful, <b>false</b> otherwise</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Delete)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static bool Delete(GiftCertificate giftCertificate)
        {
            return giftCertificate.Delete();
        }

        /// <summary>
        /// Deletes a GiftCertificate object with given id from the database
        /// </summary>
        /// <param name="giftCertificateId">Value of GiftCertificateId of the object to delete.</param>
        /// <returns><b>true</b> if delete operation is successful, <b>false</b> otherwise</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Delete)]
        public static bool Delete(Int32 giftCertificateId)
        {
            GiftCertificate giftCertificate = new GiftCertificate();
            if (giftCertificate.Load(giftCertificateId)) return giftCertificate.Delete();
            return false;
        }

        /// <summary>
        /// Inserts/Saves a GiftCertificate object to the database.
        /// </summary>
        /// <param name="giftCertificate">The GiftCertificate object to insert</param>
        /// <returns><b>SaveResult</b> enumeration that represents the result of the save operation.</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Insert)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static SaveResult Insert(GiftCertificate giftCertificate) { return giftCertificate.Save(); }

        /// <summary>
        /// Loads a GiftCertificate object for given Id from the database.
        /// </summary>
        /// <param name="giftCertificateId">Value of GiftCertificateId of the object to load.</param>
        /// <returns>If the load is successful the newly loaded GiftCertificate object is returned. If load fails null is returned.</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static GiftCertificate Load(Int32 giftCertificateId)
        {
            return GiftCertificateDataSource.Load(giftCertificateId, true);
        }

        /// <summary>
        /// Loads a GiftCertificate object for given Id from the database.
        /// </summary>
        /// <param name="giftCertificateId">Value of GiftCertificateId of the object to load.</param>
        /// <param name="useCache">If true tries to load object from cache first.</param>
        /// <returns>If the load is successful the newly loaded GiftCertificate object is returned. If load fails null is returned.</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static GiftCertificate Load(Int32 giftCertificateId, bool useCache)
        {
            if (giftCertificateId == 0) return null;
            GiftCertificate giftCertificate = null;
            string key = "GiftCertificate_" + giftCertificateId.ToString();
            if (useCache)
            {
                giftCertificate = ContextCache.GetObject(key) as GiftCertificate;
                if (giftCertificate != null) return giftCertificate;
            }
            giftCertificate = new GiftCertificate();
            if (giftCertificate.Load(giftCertificateId))
            {
                if (useCache) ContextCache.SetObject(key, giftCertificate);
                return giftCertificate;
            }
            return null;
        }

        /// <summary>
        /// Counts the number of GiftCertificate objects in result if retrieved using the given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the GiftCertificate objects that should be loaded.</param>
        /// <returns>The number of GiftCertificate objects matching the criteria</returns>
        public static int CountForCriteria(string sqlCriteria)
        {
            Database database = Token.Instance.Database;
            string whereClause = string.IsNullOrEmpty(sqlCriteria) ? string.Empty : " WHERE " + sqlCriteria;
            DbCommand selectCommand = database.GetSqlStringCommand("SELECT COUNT(*) AS TotalRecords FROM ac_GiftCertificates" + whereClause);
            return CommerceBuilder.Utility.AlwaysConvert.ToInt(database.ExecuteScalar(selectCommand));
        }

        /// <summary>
        /// Loads a collection of GiftCertificate objects from the database based on given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the objects that should be loaded.</param>
        /// <returns>A collection of GiftCertificate objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static GiftCertificateCollection LoadForCriteria(string sqlCriteria)
        {
            return LoadForCriteria(sqlCriteria, 0, 0, string.Empty);
        }

        /// <summary>
        /// Loads a collection of GiftCertificate objects from the database based on given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the objects that should be loaded.</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of GiftCertificate objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static GiftCertificateCollection LoadForCriteria(string sqlCriteria, string sortExpression)
        {
            return LoadForCriteria(sqlCriteria, 0, 0, sortExpression);
        }

        /// <summary>
        /// Loads a collection of GiftCertificate objects from the database based on given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the objects that should be loaded.</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <returns>A collection of GiftCertificate objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static GiftCertificateCollection LoadForCriteria(string sqlCriteria, int maximumRows, int startRowIndex)
        {
            return LoadForCriteria(sqlCriteria, maximumRows, startRowIndex, string.Empty);
        }

        /// <summary>
        /// Loads a collection of GiftCertificate objects from the database based on given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the objects that should be loaded.</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of GiftCertificate objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static GiftCertificateCollection  LoadForCriteria(string sqlCriteria, int maximumRows, int startRowIndex, string sortExpression)
        {
            //CREATE THE DYNAMIC SQL TO LOAD OBJECT
            StringBuilder selectQuery = new StringBuilder();
            selectQuery.Append("SELECT");
            if (maximumRows > 0) selectQuery.Append(" TOP " + (startRowIndex + maximumRows).ToString());
            selectQuery.Append(" " + GiftCertificate.GetColumnNames(string.Empty));
            selectQuery.Append(" FROM ac_GiftCertificates");
            string whereClause = string.IsNullOrEmpty(sqlCriteria) ? string.Empty : " WHERE " + sqlCriteria;
            selectQuery.Append(whereClause);
            if (!string.IsNullOrEmpty(sortExpression)) selectQuery.Append(" ORDER BY " + sortExpression);
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand(selectQuery.ToString());
            //EXECUTE THE COMMAND
            GiftCertificateCollection results = new GiftCertificateCollection();
            int thisIndex = 0;
            int rowCount = 0;
            using (IDataReader dr = database.ExecuteReader(selectCommand))
            {
                while (dr.Read() && ((maximumRows < 1) || (rowCount < maximumRows)))
                {
                    if (thisIndex >= startRowIndex)
                    {
                        GiftCertificate giftCertificate = new GiftCertificate();
                        GiftCertificate.LoadDataReader(giftCertificate, dr);
                        results.Add(giftCertificate);
                        rowCount++;
                    }
                    thisIndex++;
                }
                dr.Close();
            }
            return results;
        }

        /// <summary>
        /// Counts the number of GiftCertificate objects for the given OrderItemId in the database.
        /// <param name="orderItemId">The given OrderItemId</param>
        /// </summary>
        /// <returns>The Number of GiftCertificate objects for the given OrderItemId in the database.</returns>
        public static int CountForOrderItem(Int32 orderItemId)
        {
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand("SELECT COUNT(*) AS TotalRecords FROM ac_GiftCertificates WHERE OrderItemId = @orderItemId");
            database.AddInParameter(selectCommand, "@orderItemId", System.Data.DbType.Int32, NullableData.DbNullify(orderItemId));
            return CommerceBuilder.Utility.AlwaysConvert.ToInt(database.ExecuteScalar(selectCommand));
        }

        /// <summary>
        /// Loads a collection of GiftCertificate objects for the given OrderItemId from the database
        /// </summary>
        /// <param name="orderItemId">The given OrderItemId</param>
        /// <returns>A collection of GiftCertificate objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static GiftCertificateCollection LoadForOrderItem(Int32 orderItemId)
        {
            return LoadForOrderItem(orderItemId, 0, 0, string.Empty);
        }

        /// <summary>
        /// Loads a collection of GiftCertificate objects for the given OrderItemId from the database
        /// </summary>
        /// <param name="orderItemId">The given OrderItemId</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of GiftCertificate objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static GiftCertificateCollection LoadForOrderItem(Int32 orderItemId, string sortExpression)
        {
            return LoadForOrderItem(orderItemId, 0, 0, sortExpression);
        }

        /// <summary>
        /// Loads a collection of GiftCertificate objects for the given OrderItemId from the database
        /// </summary>
        /// <param name="orderItemId">The given OrderItemId</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <returns>A collection of GiftCertificate objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static GiftCertificateCollection LoadForOrderItem(Int32 orderItemId, int maximumRows, int startRowIndex)
        {
            return LoadForOrderItem(orderItemId, maximumRows, startRowIndex, string.Empty);
        }

        /// <summary>
        /// Loads a collection of GiftCertificate objects for the given OrderItemId from the database
        /// </summary>
        /// <param name="orderItemId">The given OrderItemId</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of GiftCertificate objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static GiftCertificateCollection LoadForOrderItem(Int32 orderItemId, int maximumRows, int startRowIndex, string sortExpression)
        {
            //CREATE THE DYNAMIC SQL TO LOAD OBJECT
            StringBuilder selectQuery = new StringBuilder();
            selectQuery.Append("SELECT");
            if (maximumRows > 0) selectQuery.Append(" TOP " + (startRowIndex + maximumRows).ToString());
            selectQuery.Append(" " + GiftCertificate.GetColumnNames(string.Empty));
            selectQuery.Append(" FROM ac_GiftCertificates");
            selectQuery.Append(" WHERE OrderItemId = @orderItemId");
            if (!string.IsNullOrEmpty(sortExpression)) selectQuery.Append(" ORDER BY " + sortExpression);
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand(selectQuery.ToString());
            database.AddInParameter(selectCommand, "@orderItemId", System.Data.DbType.Int32, NullableData.DbNullify(orderItemId));
            //EXECUTE THE COMMAND
            GiftCertificateCollection results = new GiftCertificateCollection();
            int thisIndex = 0;
            int rowCount = 0;
            using (IDataReader dr = database.ExecuteReader(selectCommand))
            {
                while (dr.Read() && ((maximumRows < 1) || (rowCount < maximumRows)))
                {
                    if (thisIndex >= startRowIndex)
                    {
                        GiftCertificate giftCertificate = new GiftCertificate();
                        GiftCertificate.LoadDataReader(giftCertificate, dr);
                        results.Add(giftCertificate);
                        rowCount++;
                    }
                    thisIndex++;
                }
                dr.Close();
            }
            return results;
        }

        /// <summary>
        /// Counts the number of GiftCertificate objects for the current store.
        /// </summary>
        /// <returns>The Number of GiftCertificate objects in the current store.</returns>
        public static int CountForStore()
        {
            int storeId = Token.Instance.StoreId;
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand("SELECT COUNT(*) AS TotalRecords FROM ac_GiftCertificates WHERE StoreId = @storeId");
            database.AddInParameter(selectCommand, "@storeId", System.Data.DbType.Int32, storeId);
            return CommerceBuilder.Utility.AlwaysConvert.ToInt(database.ExecuteScalar(selectCommand));
        }

        /// <summary>
        /// Loads a collection of GiftCertificate objects for the current store from the database
        /// </summary>
        /// <returns>A collection of GiftCertificate objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static GiftCertificateCollection LoadForStore()
        {
            return LoadForStore(0, 0, string.Empty);
        }

        /// <summary>
        /// Loads a collection of GiftCertificate objects for the current store from the database. Sorts using the given sort exrpression.
        /// </summary>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of GiftCertificate objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static GiftCertificateCollection LoadForStore(string sortExpression)
        {
            return LoadForStore(0, 0, sortExpression);
        }

        /// <summary>
        /// Loads a collection of GiftCertificate objects for the current store from the database.
        /// </summary>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <returns>A collection of GiftCertificate objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static GiftCertificateCollection LoadForStore(int maximumRows, int startRowIndex)
        {
            return LoadForStore(maximumRows, startRowIndex, string.Empty);
        }

        /// <summary>
        /// Loads a collection of GiftCertificate objects for the current store from the database. Sorts using the given sort exrpression.
        /// </summary>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of GiftCertificate objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static GiftCertificateCollection LoadForStore(int maximumRows, int startRowIndex, string sortExpression)
        {
            int storeId = Token.Instance.StoreId;
            //CREATE THE DYNAMIC SQL TO LOAD OBJECT
            StringBuilder selectQuery = new StringBuilder();
            selectQuery.Append("SELECT");
            if (maximumRows > 0) selectQuery.Append(" TOP " + (startRowIndex + maximumRows).ToString());
            selectQuery.Append(" " + GiftCertificate.GetColumnNames(string.Empty));
            selectQuery.Append(" FROM ac_GiftCertificates");
            selectQuery.Append(" WHERE StoreId = @storeId");
            if (!string.IsNullOrEmpty(sortExpression)) selectQuery.Append(" ORDER BY " + sortExpression);
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand(selectQuery.ToString());
            database.AddInParameter(selectCommand, "@storeId", System.Data.DbType.Int32, storeId);
            //EXECUTE THE COMMAND
            GiftCertificateCollection results = new GiftCertificateCollection();
            int thisIndex = 0;
            int rowCount = 0;
            using (IDataReader dr = database.ExecuteReader(selectCommand))
            {
                while (dr.Read() && ((maximumRows < 1) || (rowCount < maximumRows)))
                {
                    if (thisIndex >= startRowIndex)
                    {
                        GiftCertificate giftCertificate = new GiftCertificate();
                        GiftCertificate.LoadDataReader(giftCertificate, dr);
                        results.Add(giftCertificate);
                        rowCount++;
                    }
                    thisIndex++;
                }
                dr.Close();
            }
            return results;
        }

        /// <summary>
        /// Updates/Saves the given GiftCertificate object to the database.
        /// </summary>
        /// <param name="giftCertificate">The GiftCertificate object to update/save to database.</param>
        /// <returns><b>SaveResult</b> enumeration that represents the result of the save operation.</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Update)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static SaveResult Update(GiftCertificate giftCertificate) { return giftCertificate.Save(); }

    }
}
