//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace CommerceBuilder.Web.SiteMap
{
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sitemaps.org/schemas/sitemap/0.9", IsNullable=false)]
    public partial class urlset {
        
        private url[] urlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("url")]
        public url[] url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sitemaps.org/schemas/sitemap/0.9", IsNullable=false)]
    public partial class url {
        
        private string locField;
        
        private string lastmodField;
        
        private changefreq changefreqField;
        
        private bool changefreqFieldSpecified;
        
        private decimal priorityField;
        
        private bool priorityFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string loc {
            get {
                return this.locField;
            }
            set {
                this.locField = value;
            }
        }
        
        /// <remarks/>
        public string lastmod {
            get {
                return this.lastmodField;
            }
            set {
                this.lastmodField = value;
            }
        }
        
        /// <remarks/>
        public changefreq changefreq {
            get {
                return this.changefreqField;
            }
            set {
                this.changefreqField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool changefreqSpecified {
            get {
                return this.changefreqFieldSpecified;
            }
            set {
                this.changefreqFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool prioritySpecified {
            get {
                return this.priorityFieldSpecified;
            }
            set {
                this.priorityFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sitemaps.org/schemas/sitemap/0.9", IsNullable=false)]
    public enum changefreq {
        
        /// <remarks/>
        always,
        
        /// <remarks/>
        hourly,
        
        /// <remarks/>
        daily,
        
        /// <remarks/>
        weekly,
        
        /// <remarks/>
        monthly,
        
        /// <remarks/>
        yearly,
        
        /// <remarks/>
        never,
    }
}
