//Generated by PersistableBaseGenerator

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Text;
using CommerceBuilder.Common;
using CommerceBuilder.Data;
using CommerceBuilder.Taxes;
using CommerceBuilder.Utility;

namespace CommerceBuilder.Taxes
{
    /// <summary>
    /// This class represents a TaxRuleTaxCode object in the database.
    /// </summary>
    public partial class TaxRuleTaxCode : IPersistable
    {

#region Constructors

        /// <summary>
        /// Default Constructor
        /// </summary>
        public TaxRuleTaxCode() { }

        /// <summary>
        /// Constructor with primary key
        /// <param name="taxRuleId">Value of TaxRuleId.</param>
        /// <param name="taxCodeId">Value of TaxCodeId.</param>
        /// </summary>
        public TaxRuleTaxCode(Int32 taxRuleId, Int32 taxCodeId)
        {
            this.TaxRuleId = taxRuleId;
            this.TaxCodeId = taxCodeId;
        }

        /// <summary>
        /// Returns a coma separated list of column names in this database object.
        /// </summary>
        /// <param name="prefix">Prefix to use with column names. Leave null or empty for no prefix.</param>
        /// <returns>A coman separated list of column names for this database object.</returns>
        public static string GetColumnNames(string prefix)
        {
          if (string.IsNullOrEmpty(prefix)) prefix = string.Empty;
          else prefix = prefix + ".";
          List<string> columnNames = new List<string>();
          columnNames.Add(prefix + "TaxRuleId");
          columnNames.Add(prefix + "TaxCodeId");
          return string.Join(",", columnNames.ToArray());
        }

        /// <summary>
        /// Loads the given TaxRuleTaxCode object from the given database data reader.
        /// </summary>
        /// <param name="taxRuleTaxCode">The TaxRuleTaxCode object to load.</param>
        /// <param name="dr">The database data reader to read data from.</param>
        public static void LoadDataReader(TaxRuleTaxCode taxRuleTaxCode, IDataReader dr)
        {
            //SET FIELDS FROM ROW DATA
            taxRuleTaxCode.TaxRuleId = dr.GetInt32(0);
            taxRuleTaxCode.TaxCodeId = dr.GetInt32(1);
            taxRuleTaxCode.IsDirty = false;
        }

#endregion

        private Int32 _TaxRuleId;
        private Int32 _TaxCodeId;
        private bool _IsDirty;

        /// <summary>
        /// TaxRuleId
        /// </summary>
        [DataObjectField(true, false, false)]
        public Int32 TaxRuleId
        {
            get { return this._TaxRuleId; }
            set
            {
                if (this._TaxRuleId != value)
                {
                    this._TaxRuleId = value;
                    this.IsDirty = true;
                    this._TaxRule = null;
                }
            }
        }

        /// <summary>
        /// TaxCodeId
        /// </summary>
        [DataObjectField(true, false, false)]
        public Int32 TaxCodeId
        {
            get { return this._TaxCodeId; }
            set
            {
                if (this._TaxCodeId != value)
                {
                    this._TaxCodeId = value;
                    this.IsDirty = true;
                    this._TaxCode = null;
                }
            }
        }

        /// <summary>
        /// Indicates whether this TaxRuleTaxCode object has changed since it was loaded from the database.
        /// </summary>
        public bool IsDirty
        {
            get { return this._IsDirty; }
            set { this._IsDirty = value; }
        }

#region Parents
        private TaxCode _TaxCode;
        private TaxRule _TaxRule;

        /// <summary>
        /// The TaxCode object that this TaxRuleTaxCode object is associated with
        /// </summary>
        public TaxCode TaxCode
        {
            get
            {
                if (!this.TaxCodeLoaded)
                {
                    this._TaxCode = TaxCodeDataSource.Load(this.TaxCodeId);
                }
                return this._TaxCode;
            }
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal bool TaxCodeLoaded { get { return ((this._TaxCode != null) && (this._TaxCode.TaxCodeId == this.TaxCodeId)); } }

        /// <summary>
        /// The TaxRule object that this TaxRuleTaxCode object is associated with
        /// </summary>
        public TaxRule TaxRule
        {
            get
            {
                if (!this.TaxRuleLoaded)
                {
                    this._TaxRule = TaxRuleDataSource.Load(this.TaxRuleId);
                }
                return this._TaxRule;
            }
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal bool TaxRuleLoaded { get { return ((this._TaxRule != null) && (this._TaxRule.TaxRuleId == this.TaxRuleId)); } }

#endregion

        /// <summary>
        /// Deletes this TaxRuleTaxCode object from the database.
        /// </summary>
        /// <returns><b>true</b> if delete successful, <b>false</b> otherwise.</returns>
        public virtual bool Delete()
        {
            int recordsAffected = 0;
            StringBuilder deleteQuery = new StringBuilder();
            deleteQuery.Append("DELETE FROM ac_TaxRuleTaxCodes");
            deleteQuery.Append(" WHERE TaxRuleId = @TaxRuleId AND TaxCodeId = @TaxCodeId");
            Database database = Token.Instance.Database;
            using (DbCommand deleteCommand = database.GetSqlStringCommand(deleteQuery.ToString()))
            {
                database.AddInParameter(deleteCommand, "@TaxRuleId", System.Data.DbType.Int32, this.TaxRuleId);
                database.AddInParameter(deleteCommand, "@TaxCodeId", System.Data.DbType.Int32, this.TaxCodeId);
                recordsAffected = database.ExecuteNonQuery(deleteCommand);
            }
            return (recordsAffected > 0);
        }

        /// <summary>
        /// Load this TaxRuleTaxCode object from the database for the given primary key.
        /// </summary>
        /// <param name="taxRuleId">Value of TaxRuleId of the object to load.</param>
        /// <param name="taxCodeId">Value of TaxCodeId of the object to load.</param>
        /// <returns><b>true</b> if load is successful, <b>false</b> otherwise</returns>
        public virtual bool Load(Int32 taxRuleId, Int32 taxCodeId)
        {
            this.TaxRuleId = taxRuleId;
            this.TaxCodeId = taxCodeId;
            this.IsDirty = false;
            return true;
        }

        /// <summary>
        /// Saves this TaxRuleTaxCode object to the database.
        /// </summary>
        /// <returns><b>SaveResult</b> enumeration that represents the result of the save operation.</returns>
        public virtual SaveResult Save()
        {
            if (this.IsDirty)
            {
                Database database = Token.Instance.Database;
                bool recordExists = true;
                
                //generate key(s) if needed
                if (recordExists) {
                    //verify whether record is already present
                    StringBuilder selectQuery = new StringBuilder();
                    selectQuery.Append("SELECT COUNT(*) As RecordCount FROM ac_TaxRuleTaxCodes");
                    selectQuery.Append(" WHERE TaxRuleId = @TaxRuleId AND TaxCodeId = @TaxCodeId");
                    using (DbCommand selectCommand = database.GetSqlStringCommand(selectQuery.ToString()))
                    {
                        database.AddInParameter(selectCommand, "@TaxRuleId", System.Data.DbType.Int32, this.TaxRuleId);
                        database.AddInParameter(selectCommand, "@TaxCodeId", System.Data.DbType.Int32, this.TaxCodeId);
                        if ((int)database.ExecuteScalar(selectCommand) == 0)
                        {
                            recordExists = false;
                        }
                    }
                }

                if (recordExists)
                {
                    //RECORD ALREADY EXISTS IN DATABASE
                    this.IsDirty = false;
                    return SaveResult.RecordUpdated;
                }
                else
                {
                    //INSERT
                    StringBuilder insertQuery = new StringBuilder();
                    insertQuery.Append("INSERT INTO ac_TaxRuleTaxCodes (TaxRuleId, TaxCodeId)");
                    insertQuery.Append(" VALUES (@TaxRuleId, @TaxCodeId)");
                    using (DbCommand insertCommand = database.GetSqlStringCommand(insertQuery.ToString()))
                    {
                        database.AddInParameter(insertCommand, "@TaxRuleId", System.Data.DbType.Int32, this.TaxRuleId);
                        database.AddInParameter(insertCommand, "@TaxCodeId", System.Data.DbType.Int32, this.TaxCodeId);
                        int recordsAffected = database.ExecuteNonQuery(insertCommand);
                        //OBJECT IS NOT DIRTY IF RECORD WAS INSERTED
                        this.IsDirty = (recordsAffected == 0);
                        if (this.IsDirty) { return SaveResult.Failed; }
                        return SaveResult.RecordInserted;
                    }
                }

            }

            //SAVE IS SUCCESSFUL IF OBJECT IS NOT DIRTY
            return SaveResult.NotDirty;
        }

     }
}
