//Generated by DataSourceBaseGenerator

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Text;
using CommerceBuilder.Common;
using CommerceBuilder.Data;
using CommerceBuilder.Utility;

namespace CommerceBuilder.Marketing
{
    /// <summary>
    /// DataSource class for EmailListUser objects
    /// </summary>
    public partial class EmailListUserDataSource
    {
        /// <summary>
        /// Deletes a EmailListUser object from the database
        /// </summary>
        /// <param name="emailListUser">The EmailListUser object to delete</param>
        /// <returns><b>true</b> if delete operation is successful, <b>false</b> otherwise</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Delete)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static bool Delete(EmailListUser emailListUser)
        {
            return emailListUser.Delete();
        }

        /// <summary>
        /// Deletes a EmailListUser object with given id from the database
        /// </summary>
        /// <param name="emailListId">Value of EmailListId of the object to delete.</param>
        /// <param name="email">Value of Email of the object to delete.</param>
        /// <returns><b>true</b> if delete operation is successful, <b>false</b> otherwise</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Delete)]
        public static bool Delete(Int32 emailListId, String email)
        {
            EmailListUser emailListUser = new EmailListUser();
            if (emailListUser.Load(emailListId, email)) return emailListUser.Delete();
            return false;
        }

        /// <summary>
        /// Inserts/Saves a EmailListUser object to the database.
        /// </summary>
        /// <param name="emailListUser">The EmailListUser object to insert</param>
        /// <returns><b>SaveResult</b> enumeration that represents the result of the save operation.</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Insert)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static SaveResult Insert(EmailListUser emailListUser) { return emailListUser.Save(); }

        /// <summary>
        /// Loads a EmailListUser object for given key from the database.
        /// </summary>
        /// <param name="emailListId">Value of EmailListId of the object to load.</param>
        /// <param name="email">Value of Email of the object to load.</param>
        /// <returns>If the load is successful the newly loaded EmailListUser object is returned. If load fails null is returned.</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static EmailListUser Load(Int32 emailListId, String email)
        {
            EmailListUser emailListUser = new EmailListUser();
            if (emailListUser.Load(emailListId, email)) return emailListUser;
            return null;
        }

        /// <summary>
        /// Counts the number of EmailListUser objects in result if retrieved using the given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the EmailListUser objects that should be loaded.</param>
        /// <returns>The number of EmailListUser objects matching the criteria</returns>
        public static int CountForCriteria(string sqlCriteria)
        {
            Database database = Token.Instance.Database;
            string whereClause = string.IsNullOrEmpty(sqlCriteria) ? string.Empty : " WHERE " + sqlCriteria;
            DbCommand selectCommand = database.GetSqlStringCommand("SELECT COUNT(*) AS TotalRecords FROM ac_EmailListUsers" + whereClause);
            return CommerceBuilder.Utility.AlwaysConvert.ToInt(database.ExecuteScalar(selectCommand));
        }

        /// <summary>
        /// Loads a collection of EmailListUser objects from the database based on given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the objects that should be loaded.</param>
        /// <returns>A collection of EmailListUser objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static EmailListUserCollection LoadForCriteria(string sqlCriteria)
        {
            return LoadForCriteria(sqlCriteria, 0, 0, string.Empty);
        }

        /// <summary>
        /// Loads a collection of EmailListUser objects from the database based on given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the objects that should be loaded.</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of EmailListUser objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static EmailListUserCollection LoadForCriteria(string sqlCriteria, string sortExpression)
        {
            return LoadForCriteria(sqlCriteria, 0, 0, sortExpression);
        }

        /// <summary>
        /// Loads a collection of EmailListUser objects from the database based on given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the objects that should be loaded.</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <returns>A collection of EmailListUser objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static EmailListUserCollection LoadForCriteria(string sqlCriteria, int maximumRows, int startRowIndex)
        {
            return LoadForCriteria(sqlCriteria, maximumRows, startRowIndex, string.Empty);
        }

        /// <summary>
        /// Loads a collection of EmailListUser objects from the database based on given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the objects that should be loaded.</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of EmailListUser objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static EmailListUserCollection  LoadForCriteria(string sqlCriteria, int maximumRows, int startRowIndex, string sortExpression)
        {
            //CREATE THE DYNAMIC SQL TO LOAD OBJECT
            StringBuilder selectQuery = new StringBuilder();
            selectQuery.Append("SELECT");
            if (maximumRows > 0) selectQuery.Append(" TOP " + (startRowIndex + maximumRows).ToString());
            selectQuery.Append(" " + EmailListUser.GetColumnNames(string.Empty));
            selectQuery.Append(" FROM ac_EmailListUsers");
            string whereClause = string.IsNullOrEmpty(sqlCriteria) ? string.Empty : " WHERE " + sqlCriteria;
            selectQuery.Append(whereClause);
            if (!string.IsNullOrEmpty(sortExpression)) selectQuery.Append(" ORDER BY " + sortExpression);
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand(selectQuery.ToString());
            //EXECUTE THE COMMAND
            EmailListUserCollection results = new EmailListUserCollection();
            int thisIndex = 0;
            int rowCount = 0;
            using (IDataReader dr = database.ExecuteReader(selectCommand))
            {
                while (dr.Read() && ((maximumRows < 1) || (rowCount < maximumRows)))
                {
                    if (thisIndex >= startRowIndex)
                    {
                        EmailListUser emailListUser = new EmailListUser();
                        EmailListUser.LoadDataReader(emailListUser, dr);
                        results.Add(emailListUser);
                        rowCount++;
                    }
                    thisIndex++;
                }
                dr.Close();
            }
            return results;
        }

        /// <summary>
        /// Counts the number of EmailListUser objects for the given EmailListId in the database.
        /// <param name="emailListId">The given EmailListId</param>
        /// </summary>
        /// <returns>The Number of EmailListUser objects for the given EmailListId in the database.</returns>
        public static int CountForEmailList(Int32 emailListId)
        {
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand("SELECT COUNT(*) AS TotalRecords FROM ac_EmailListUsers WHERE EmailListId = @emailListId");
            database.AddInParameter(selectCommand, "@emailListId", System.Data.DbType.Int32, emailListId);
            return CommerceBuilder.Utility.AlwaysConvert.ToInt(database.ExecuteScalar(selectCommand));
        }

        /// <summary>
        /// Loads a collection of EmailListUser objects for the given EmailListId from the database
        /// </summary>
        /// <param name="emailListId">The given EmailListId</param>
        /// <returns>A collection of EmailListUser objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static EmailListUserCollection LoadForEmailList(Int32 emailListId)
        {
            return LoadForEmailList(emailListId, 0, 0, string.Empty);
        }

        /// <summary>
        /// Loads a collection of EmailListUser objects for the given EmailListId from the database
        /// </summary>
        /// <param name="emailListId">The given EmailListId</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of EmailListUser objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static EmailListUserCollection LoadForEmailList(Int32 emailListId, string sortExpression)
        {
            return LoadForEmailList(emailListId, 0, 0, sortExpression);
        }

        /// <summary>
        /// Loads a collection of EmailListUser objects for the given EmailListId from the database
        /// </summary>
        /// <param name="emailListId">The given EmailListId</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <returns>A collection of EmailListUser objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static EmailListUserCollection LoadForEmailList(Int32 emailListId, int maximumRows, int startRowIndex)
        {
            return LoadForEmailList(emailListId, maximumRows, startRowIndex, string.Empty);
        }

        /// <summary>
        /// Loads a collection of EmailListUser objects for the given EmailListId from the database
        /// </summary>
        /// <param name="emailListId">The given EmailListId</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of EmailListUser objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static EmailListUserCollection LoadForEmailList(Int32 emailListId, int maximumRows, int startRowIndex, string sortExpression)
        {
            //CREATE THE DYNAMIC SQL TO LOAD OBJECT
            StringBuilder selectQuery = new StringBuilder();
            selectQuery.Append("SELECT");
            if (maximumRows > 0) selectQuery.Append(" TOP " + (startRowIndex + maximumRows).ToString());
            selectQuery.Append(" " + EmailListUser.GetColumnNames(string.Empty));
            selectQuery.Append(" FROM ac_EmailListUsers");
            selectQuery.Append(" WHERE EmailListId = @emailListId");
            if (!string.IsNullOrEmpty(sortExpression)) selectQuery.Append(" ORDER BY " + sortExpression);
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand(selectQuery.ToString());
            database.AddInParameter(selectCommand, "@emailListId", System.Data.DbType.Int32, emailListId);
            //EXECUTE THE COMMAND
            EmailListUserCollection results = new EmailListUserCollection();
            int thisIndex = 0;
            int rowCount = 0;
            using (IDataReader dr = database.ExecuteReader(selectCommand))
            {
                while (dr.Read() && ((maximumRows < 1) || (rowCount < maximumRows)))
                {
                    if (thisIndex >= startRowIndex)
                    {
                        EmailListUser emailListUser = new EmailListUser();
                        EmailListUser.LoadDataReader(emailListUser, dr);
                        results.Add(emailListUser);
                        rowCount++;
                    }
                    thisIndex++;
                }
                dr.Close();
            }
            return results;
        }

        /// <summary>
        /// Updates/Saves the given EmailListUser object to the database.
        /// </summary>
        /// <param name="emailListUser">The EmailListUser object to update/save to database.</param>
        /// <returns><b>SaveResult</b> enumeration that represents the result of the save operation.</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Update)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static SaveResult Update(EmailListUser emailListUser) { return emailListUser.Save(); }

    }
}
