//Generated by DataSourceBaseGenerator

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Text;
using CommerceBuilder.Common;
using CommerceBuilder.Data;
using CommerceBuilder.Utility;

namespace CommerceBuilder.Orders
{
    /// <summary>
    /// DataSource class for BasketItemInput objects
    /// </summary>
    public partial class BasketItemInputDataSource
    {
        /// <summary>
        /// Deletes a BasketItemInput object from the database
        /// </summary>
        /// <param name="basketItemInput">The BasketItemInput object to delete</param>
        /// <returns><b>true</b> if delete operation is successful, <b>false</b> otherwise</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Delete)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static bool Delete(BasketItemInput basketItemInput)
        {
            return basketItemInput.Delete();
        }

        /// <summary>
        /// Deletes a BasketItemInput object with given id from the database
        /// </summary>
        /// <param name="basketItemInputId">Value of BasketItemInputId of the object to delete.</param>
        /// <returns><b>true</b> if delete operation is successful, <b>false</b> otherwise</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Delete)]
        public static bool Delete(Int32 basketItemInputId)
        {
            BasketItemInput basketItemInput = new BasketItemInput();
            if (basketItemInput.Load(basketItemInputId)) return basketItemInput.Delete();
            return false;
        }

        /// <summary>
        /// Inserts/Saves a BasketItemInput object to the database.
        /// </summary>
        /// <param name="basketItemInput">The BasketItemInput object to insert</param>
        /// <returns><b>SaveResult</b> enumeration that represents the result of the save operation.</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Insert)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static SaveResult Insert(BasketItemInput basketItemInput) { return basketItemInput.Save(); }

        /// <summary>
        /// Loads a BasketItemInput object for given Id from the database.
        /// </summary>
        /// <param name="basketItemInputId">Value of BasketItemInputId of the object to load.</param>
        /// <returns>If the load is successful the newly loaded BasketItemInput object is returned. If load fails null is returned.</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static BasketItemInput Load(Int32 basketItemInputId)
        {
            return BasketItemInputDataSource.Load(basketItemInputId, true);
        }

        /// <summary>
        /// Loads a BasketItemInput object for given Id from the database.
        /// </summary>
        /// <param name="basketItemInputId">Value of BasketItemInputId of the object to load.</param>
        /// <param name="useCache">If true tries to load object from cache first.</param>
        /// <returns>If the load is successful the newly loaded BasketItemInput object is returned. If load fails null is returned.</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static BasketItemInput Load(Int32 basketItemInputId, bool useCache)
        {
            if (basketItemInputId == 0) return null;
            BasketItemInput basketItemInput = null;
            string key = "BasketItemInput_" + basketItemInputId.ToString();
            if (useCache)
            {
                basketItemInput = ContextCache.GetObject(key) as BasketItemInput;
                if (basketItemInput != null) return basketItemInput;
            }
            basketItemInput = new BasketItemInput();
            if (basketItemInput.Load(basketItemInputId))
            {
                if (useCache) ContextCache.SetObject(key, basketItemInput);
                return basketItemInput;
            }
            return null;
        }

        /// <summary>
        /// Counts the number of BasketItemInput objects in result if retrieved using the given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the BasketItemInput objects that should be loaded.</param>
        /// <returns>The number of BasketItemInput objects matching the criteria</returns>
        public static int CountForCriteria(string sqlCriteria)
        {
            Database database = Token.Instance.Database;
            string whereClause = string.IsNullOrEmpty(sqlCriteria) ? string.Empty : " WHERE " + sqlCriteria;
            DbCommand selectCommand = database.GetSqlStringCommand("SELECT COUNT(*) AS TotalRecords FROM ac_BasketItemInputs" + whereClause);
            return CommerceBuilder.Utility.AlwaysConvert.ToInt(database.ExecuteScalar(selectCommand));
        }

        /// <summary>
        /// Loads a collection of BasketItemInput objects from the database based on given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the objects that should be loaded.</param>
        /// <returns>A collection of BasketItemInput objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static BasketItemInputCollection LoadForCriteria(string sqlCriteria)
        {
            return LoadForCriteria(sqlCriteria, 0, 0, string.Empty);
        }

        /// <summary>
        /// Loads a collection of BasketItemInput objects from the database based on given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the objects that should be loaded.</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of BasketItemInput objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static BasketItemInputCollection LoadForCriteria(string sqlCriteria, string sortExpression)
        {
            return LoadForCriteria(sqlCriteria, 0, 0, sortExpression);
        }

        /// <summary>
        /// Loads a collection of BasketItemInput objects from the database based on given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the objects that should be loaded.</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <returns>A collection of BasketItemInput objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static BasketItemInputCollection LoadForCriteria(string sqlCriteria, int maximumRows, int startRowIndex)
        {
            return LoadForCriteria(sqlCriteria, maximumRows, startRowIndex, string.Empty);
        }

        /// <summary>
        /// Loads a collection of BasketItemInput objects from the database based on given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the objects that should be loaded.</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of BasketItemInput objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static BasketItemInputCollection  LoadForCriteria(string sqlCriteria, int maximumRows, int startRowIndex, string sortExpression)
        {
            //CREATE THE DYNAMIC SQL TO LOAD OBJECT
            StringBuilder selectQuery = new StringBuilder();
            selectQuery.Append("SELECT");
            if (maximumRows > 0) selectQuery.Append(" TOP " + (startRowIndex + maximumRows).ToString());
            selectQuery.Append(" " + BasketItemInput.GetColumnNames(string.Empty));
            selectQuery.Append(" FROM ac_BasketItemInputs");
            string whereClause = string.IsNullOrEmpty(sqlCriteria) ? string.Empty : " WHERE " + sqlCriteria;
            selectQuery.Append(whereClause);
            if (!string.IsNullOrEmpty(sortExpression)) selectQuery.Append(" ORDER BY " + sortExpression);
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand(selectQuery.ToString());
            //EXECUTE THE COMMAND
            BasketItemInputCollection results = new BasketItemInputCollection();
            int thisIndex = 0;
            int rowCount = 0;
            using (IDataReader dr = database.ExecuteReader(selectCommand))
            {
                while (dr.Read() && ((maximumRows < 1) || (rowCount < maximumRows)))
                {
                    if (thisIndex >= startRowIndex)
                    {
                        BasketItemInput basketItemInput = new BasketItemInput();
                        BasketItemInput.LoadDataReader(basketItemInput, dr);
                        results.Add(basketItemInput);
                        rowCount++;
                    }
                    thisIndex++;
                }
                dr.Close();
            }
            return results;
        }

        /// <summary>
        /// Counts the number of BasketItemInput objects for the given BasketItemId in the database.
        /// <param name="basketItemId">The given BasketItemId</param>
        /// </summary>
        /// <returns>The Number of BasketItemInput objects for the given BasketItemId in the database.</returns>
        public static int CountForBasketItem(Int32 basketItemId)
        {
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand("SELECT COUNT(*) AS TotalRecords FROM ac_BasketItemInputs WHERE BasketItemId = @basketItemId");
            database.AddInParameter(selectCommand, "@basketItemId", System.Data.DbType.Int32, basketItemId);
            return CommerceBuilder.Utility.AlwaysConvert.ToInt(database.ExecuteScalar(selectCommand));
        }

        /// <summary>
        /// Loads a collection of BasketItemInput objects for the given BasketItemId from the database
        /// </summary>
        /// <param name="basketItemId">The given BasketItemId</param>
        /// <returns>A collection of BasketItemInput objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static BasketItemInputCollection LoadForBasketItem(Int32 basketItemId)
        {
            return LoadForBasketItem(basketItemId, 0, 0, string.Empty);
        }

        /// <summary>
        /// Loads a collection of BasketItemInput objects for the given BasketItemId from the database
        /// </summary>
        /// <param name="basketItemId">The given BasketItemId</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of BasketItemInput objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static BasketItemInputCollection LoadForBasketItem(Int32 basketItemId, string sortExpression)
        {
            return LoadForBasketItem(basketItemId, 0, 0, sortExpression);
        }

        /// <summary>
        /// Loads a collection of BasketItemInput objects for the given BasketItemId from the database
        /// </summary>
        /// <param name="basketItemId">The given BasketItemId</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <returns>A collection of BasketItemInput objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static BasketItemInputCollection LoadForBasketItem(Int32 basketItemId, int maximumRows, int startRowIndex)
        {
            return LoadForBasketItem(basketItemId, maximumRows, startRowIndex, string.Empty);
        }

        /// <summary>
        /// Loads a collection of BasketItemInput objects for the given BasketItemId from the database
        /// </summary>
        /// <param name="basketItemId">The given BasketItemId</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of BasketItemInput objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static BasketItemInputCollection LoadForBasketItem(Int32 basketItemId, int maximumRows, int startRowIndex, string sortExpression)
        {
            //CREATE THE DYNAMIC SQL TO LOAD OBJECT
            StringBuilder selectQuery = new StringBuilder();
            selectQuery.Append("SELECT");
            if (maximumRows > 0) selectQuery.Append(" TOP " + (startRowIndex + maximumRows).ToString());
            selectQuery.Append(" " + BasketItemInput.GetColumnNames(string.Empty));
            selectQuery.Append(" FROM ac_BasketItemInputs");
            selectQuery.Append(" WHERE BasketItemId = @basketItemId");
            if (!string.IsNullOrEmpty(sortExpression)) selectQuery.Append(" ORDER BY " + sortExpression);
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand(selectQuery.ToString());
            database.AddInParameter(selectCommand, "@basketItemId", System.Data.DbType.Int32, basketItemId);
            //EXECUTE THE COMMAND
            BasketItemInputCollection results = new BasketItemInputCollection();
            int thisIndex = 0;
            int rowCount = 0;
            using (IDataReader dr = database.ExecuteReader(selectCommand))
            {
                while (dr.Read() && ((maximumRows < 1) || (rowCount < maximumRows)))
                {
                    if (thisIndex >= startRowIndex)
                    {
                        BasketItemInput basketItemInput = new BasketItemInput();
                        BasketItemInput.LoadDataReader(basketItemInput, dr);
                        results.Add(basketItemInput);
                        rowCount++;
                    }
                    thisIndex++;
                }
                dr.Close();
            }
            return results;
        }

        /// <summary>
        /// Counts the number of BasketItemInput objects for the given InputFieldId in the database.
        /// <param name="inputFieldId">The given InputFieldId</param>
        /// </summary>
        /// <returns>The Number of BasketItemInput objects for the given InputFieldId in the database.</returns>
        public static int CountForInputField(Int32 inputFieldId)
        {
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand("SELECT COUNT(*) AS TotalRecords FROM ac_BasketItemInputs WHERE InputFieldId = @inputFieldId");
            database.AddInParameter(selectCommand, "@inputFieldId", System.Data.DbType.Int32, inputFieldId);
            return CommerceBuilder.Utility.AlwaysConvert.ToInt(database.ExecuteScalar(selectCommand));
        }

        /// <summary>
        /// Loads a collection of BasketItemInput objects for the given InputFieldId from the database
        /// </summary>
        /// <param name="inputFieldId">The given InputFieldId</param>
        /// <returns>A collection of BasketItemInput objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static BasketItemInputCollection LoadForInputField(Int32 inputFieldId)
        {
            return LoadForInputField(inputFieldId, 0, 0, string.Empty);
        }

        /// <summary>
        /// Loads a collection of BasketItemInput objects for the given InputFieldId from the database
        /// </summary>
        /// <param name="inputFieldId">The given InputFieldId</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of BasketItemInput objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static BasketItemInputCollection LoadForInputField(Int32 inputFieldId, string sortExpression)
        {
            return LoadForInputField(inputFieldId, 0, 0, sortExpression);
        }

        /// <summary>
        /// Loads a collection of BasketItemInput objects for the given InputFieldId from the database
        /// </summary>
        /// <param name="inputFieldId">The given InputFieldId</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <returns>A collection of BasketItemInput objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static BasketItemInputCollection LoadForInputField(Int32 inputFieldId, int maximumRows, int startRowIndex)
        {
            return LoadForInputField(inputFieldId, maximumRows, startRowIndex, string.Empty);
        }

        /// <summary>
        /// Loads a collection of BasketItemInput objects for the given InputFieldId from the database
        /// </summary>
        /// <param name="inputFieldId">The given InputFieldId</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of BasketItemInput objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static BasketItemInputCollection LoadForInputField(Int32 inputFieldId, int maximumRows, int startRowIndex, string sortExpression)
        {
            //CREATE THE DYNAMIC SQL TO LOAD OBJECT
            StringBuilder selectQuery = new StringBuilder();
            selectQuery.Append("SELECT");
            if (maximumRows > 0) selectQuery.Append(" TOP " + (startRowIndex + maximumRows).ToString());
            selectQuery.Append(" " + BasketItemInput.GetColumnNames(string.Empty));
            selectQuery.Append(" FROM ac_BasketItemInputs");
            selectQuery.Append(" WHERE InputFieldId = @inputFieldId");
            if (!string.IsNullOrEmpty(sortExpression)) selectQuery.Append(" ORDER BY " + sortExpression);
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand(selectQuery.ToString());
            database.AddInParameter(selectCommand, "@inputFieldId", System.Data.DbType.Int32, inputFieldId);
            //EXECUTE THE COMMAND
            BasketItemInputCollection results = new BasketItemInputCollection();
            int thisIndex = 0;
            int rowCount = 0;
            using (IDataReader dr = database.ExecuteReader(selectCommand))
            {
                while (dr.Read() && ((maximumRows < 1) || (rowCount < maximumRows)))
                {
                    if (thisIndex >= startRowIndex)
                    {
                        BasketItemInput basketItemInput = new BasketItemInput();
                        BasketItemInput.LoadDataReader(basketItemInput, dr);
                        results.Add(basketItemInput);
                        rowCount++;
                    }
                    thisIndex++;
                }
                dr.Close();
            }
            return results;
        }

        /// <summary>
        /// Updates/Saves the given BasketItemInput object to the database.
        /// </summary>
        /// <param name="basketItemInput">The BasketItemInput object to update/save to database.</param>
        /// <returns><b>SaveResult</b> enumeration that represents the result of the save operation.</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Update)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static SaveResult Update(BasketItemInput basketItemInput) { return basketItemInput.Save(); }

    }
}
