//Generated by PersistableBaseGenerator

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Text;
using CommerceBuilder.Common;
using CommerceBuilder.Data;
using CommerceBuilder.Products;
using CommerceBuilder.Stores;
using CommerceBuilder.Utility;

namespace CommerceBuilder.Products
{
    /// <summary>
    /// This class represents a Vendor object in the database.
    /// </summary>
    public partial class Vendor : IPersistable
    {

#region Constructors

        /// <summary>
        /// Default Constructor
        /// </summary>
        public Vendor() { }

        /// <summary>
        /// Constructor with primary key
        /// <param name="vendorId">Value of VendorId.</param>
        /// </summary>
        public Vendor(Int32 vendorId)
        {
            this.VendorId = vendorId;
        }

        /// <summary>
        /// Returns a coma separated list of column names in this database object.
        /// </summary>
        /// <param name="prefix">Prefix to use with column names. Leave null or empty for no prefix.</param>
        /// <returns>A coman separated list of column names for this database object.</returns>
        public static string GetColumnNames(string prefix)
        {
          if (string.IsNullOrEmpty(prefix)) prefix = string.Empty;
          else prefix = prefix + ".";
          List<string> columnNames = new List<string>();
          columnNames.Add(prefix + "VendorId");
          columnNames.Add(prefix + "StoreId");
          columnNames.Add(prefix + "Name");
          columnNames.Add(prefix + "Email");
          return string.Join(",", columnNames.ToArray());
        }

        /// <summary>
        /// Loads the given Vendor object from the given database data reader.
        /// </summary>
        /// <param name="vendor">The Vendor object to load.</param>
        /// <param name="dr">The database data reader to read data from.</param>
        public static void LoadDataReader(Vendor vendor, IDataReader dr)
        {
            //SET FIELDS FROM ROW DATA
            vendor.VendorId = dr.GetInt32(0);
            vendor.StoreId = dr.GetInt32(1);
            vendor.Name = dr.GetString(2);
            vendor.Email = NullableData.GetString(dr, 3);
            vendor.IsDirty = false;
        }

#endregion

        private Int32 _VendorId;
        private Int32 _StoreId;
        private String _Name = string.Empty;
        private String _Email = string.Empty;
        private bool _IsDirty;

        /// <summary>
        /// VendorId
        /// </summary>
        [DataObjectField(true, true, false)]
        public Int32 VendorId
        {
            get { return this._VendorId; }
            set
            {
                if (this._VendorId != value)
                {
                    this._VendorId = value;
                    this.IsDirty = true;
                    this.EnsureChildProperties();
                }
            }
        }

        /// <summary>
        /// StoreId
        /// </summary>
        public Int32 StoreId
        {
            get { return this._StoreId; }
            set
            {
                if (this._StoreId != value)
                {
                    this._StoreId = value;
                    this.IsDirty = true;
                    this._Store = null;
                }
            }
        }

        /// <summary>
        /// Name
        /// </summary>
        public String Name
        {
            get { return this._Name; }
            set
            {
                if (this._Name != value)
                {
                    this._Name = value;
                    this.IsDirty = true;
                }
            }
        }

        /// <summary>
        /// Email
        /// </summary>
        public String Email
        {
            get { return this._Email; }
            set
            {
                if (this._Email != value)
                {
                    this._Email = value;
                    this.IsDirty = true;
                }
            }
        }

        /// <summary>
        /// Indicates whether this Vendor object has changed since it was loaded from the database.
        /// </summary>
        public bool IsDirty
        {
            get
            {
                if (this._IsDirty) return true;
                if (this.ProductsLoaded && this.Products.IsDirty) return true;
                if (this.VendorGroupsLoaded && this.VendorGroups.IsDirty) return true;
                return false;
            }
            set { this._IsDirty = value; }
        }

        /// <summary>
        /// Ensures that child objects of this Vendor are properly associated with this Vendor object.
        /// </summary>
        public virtual void EnsureChildProperties()
        {
            if (this.ProductsLoaded) { foreach (Product product in this.Products) { product.VendorId = this.VendorId; } }
            if (this.VendorGroupsLoaded) { foreach (VendorGroup vendorGroup in this.VendorGroups) { vendorGroup.VendorId = this.VendorId; } }
        }

#region Parents
        private Store _Store;

        /// <summary>
        /// The Store object that this Vendor object is associated with
        /// </summary>
        public Store Store
        {
            get
            {
                if (!this.StoreLoaded)
                {
                    this._Store = StoreDataSource.Load(this.StoreId);
                }
                return this._Store;
            }
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal bool StoreLoaded { get { return ((this._Store != null) && (this._Store.StoreId == this.StoreId)); } }

#endregion

#region Children
        private ProductCollection _Products;

        /// <summary>
        /// A collection of Product objects associated with this Vendor object.
        /// </summary>
        public ProductCollection Products
        {
            get
            {
                if (!this.ProductsLoaded)
                {
                    this._Products = ProductDataSource.LoadForVendor(this.VendorId);
                }
                return this._Products;
            }
        }
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal bool ProductsLoaded { get { return (this._Products != null); } }

#endregion

#region Associations
        private VendorGroupCollection _VendorGroups;

        /// <summary>
        /// A collection of VendorGroup objects associated with this Vendor object.
        /// </summary>
        public VendorGroupCollection VendorGroups
        {
            get
            {
                if (!this.VendorGroupsLoaded)
                {
                    this._VendorGroups = VendorGroupDataSource.LoadForVendor(this.VendorId);
                }
                return this._VendorGroups;
            }
        }
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal bool VendorGroupsLoaded { get { return (this._VendorGroups != null); } }
#endregion

        /// <summary>
        /// Deletes this Vendor object from the database.
        /// </summary>
        /// <returns><b>true</b> if delete successful, <b>false</b> otherwise.</returns>
        protected bool BaseDelete()
        {
            int recordsAffected = 0;
            StringBuilder deleteQuery = new StringBuilder();
            deleteQuery.Append("DELETE FROM ac_Vendors");
            deleteQuery.Append(" WHERE VendorId = @VendorId");
            Database database = Token.Instance.Database;
            using (DbCommand deleteCommand = database.GetSqlStringCommand(deleteQuery.ToString()))
            {
                database.AddInParameter(deleteCommand, "@VendorId", System.Data.DbType.Int32, this.VendorId);
                recordsAffected = database.ExecuteNonQuery(deleteCommand);
            }
            return (recordsAffected > 0);
        }


        /// <summary>
        /// Load this Vendor object from the database for the given primary key.
        /// </summary>
        /// <param name="vendorId">Value of VendorId of the object to load.</param>
        /// <returns><b>true</b> if load is successful, <b>false</b> otherwise</returns>
        public virtual bool Load(Int32 vendorId)
        {
            bool result = false;
            this.VendorId = vendorId;
            //CREATE THE DYNAMIC SQL TO LOAD OBJECT
            StringBuilder selectQuery = new StringBuilder();
            selectQuery.Append("SELECT " + GetColumnNames(string.Empty));
            selectQuery.Append(" FROM ac_Vendors");
            selectQuery.Append(" WHERE VendorId = @vendorId");
            selectQuery.Append(" AND StoreId = @storeId");
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand(selectQuery.ToString());
            database.AddInParameter(selectCommand, "@vendorId", System.Data.DbType.Int32, vendorId);
            database.AddInParameter(selectCommand, "@storeId", System.Data.DbType.Int32, Token.Instance.StoreId);
            //EXECUTE THE COMMAND
            using (IDataReader dr = database.ExecuteReader(selectCommand))
            {
                if (dr.Read())
                {
                    result = true;
                    LoadDataReader(this, dr);;
                }
                dr.Close();
            }
            return result;
        }

        /// <summary>
        /// Saves this Vendor object to the database.
        /// </summary>
        /// <returns><b>SaveResult</b> enumeration that represents the result of the save operation.</returns>
        public virtual SaveResult Save()
        {
            if (this.IsDirty)
            {
                Database database = Token.Instance.Database;
                bool recordExists = true;
                
                //SET EMPTY STOREID TO CURRENT CONTEXT
                if (this.StoreId == 0) this.StoreId = Token.Instance.StoreId;
                if (this.VendorId == 0) recordExists = false;

                if (recordExists) {
                    //verify whether record is already present
                    StringBuilder selectQuery = new StringBuilder();
                    selectQuery.Append("SELECT COUNT(*) As RecordCount FROM ac_Vendors");
                    selectQuery.Append(" WHERE VendorId = @VendorId");
                    using (DbCommand selectCommand = database.GetSqlStringCommand(selectQuery.ToString()))
                    {
                        database.AddInParameter(selectCommand, "@VendorId", System.Data.DbType.Int32, this.VendorId);
                        if ((int)database.ExecuteScalar(selectCommand) == 0)
                        {
                            recordExists = false;
                        }
                    }
                }

                int result = 0;
                if (recordExists)
                {
                    //UPDATE
                    StringBuilder updateQuery = new StringBuilder();
                    updateQuery.Append("UPDATE ac_Vendors SET ");
                    updateQuery.Append("StoreId = @StoreId");
                    updateQuery.Append(", Name = @Name");
                    updateQuery.Append(", Email = @Email");
                    updateQuery.Append(" WHERE VendorId = @VendorId");
                    using (DbCommand updateCommand = database.GetSqlStringCommand(updateQuery.ToString()))
                    {
                        database.AddInParameter(updateCommand, "@VendorId", System.Data.DbType.Int32, this.VendorId);
                        database.AddInParameter(updateCommand, "@StoreId", System.Data.DbType.Int32, this.StoreId);
                        database.AddInParameter(updateCommand, "@Name", System.Data.DbType.String, this.Name);
                        database.AddInParameter(updateCommand, "@Email", System.Data.DbType.String, NullableData.DbNullify(this.Email));
                        //RESULT IS NUMBER OF RECORDS AFFECTED
                        result = database.ExecuteNonQuery(updateCommand);
                    }
                }
                else
                {
                    //INSERT
                    StringBuilder insertQuery = new StringBuilder();
                    insertQuery.Append("INSERT INTO ac_Vendors (StoreId, Name, Email)");
                    insertQuery.Append(" VALUES (@StoreId, @Name, @Email)");
                    insertQuery.Append("; SELECT Scope_Identity()");
                    using (DbCommand insertCommand = database.GetSqlStringCommand(insertQuery.ToString()))
                    {
                        database.AddInParameter(insertCommand, "@VendorId", System.Data.DbType.Int32, this.VendorId);
                        database.AddInParameter(insertCommand, "@StoreId", System.Data.DbType.Int32, this.StoreId);
                        database.AddInParameter(insertCommand, "@Name", System.Data.DbType.String, this.Name);
                        database.AddInParameter(insertCommand, "@Email", System.Data.DbType.String, NullableData.DbNullify(this.Email));
                        //RESULT IS NEW IDENTITY;
                        result = AlwaysConvert.ToInt(database.ExecuteScalar(insertCommand));
                        this._VendorId = result;
                    }
                }
                this.SaveChildren();

                //OBJECT IS DIRTY IF NO RECORDS WERE UPDATED OR INSERTED
                this.IsDirty = (result == 0);
                if (this.IsDirty) { return SaveResult.Failed; }
                else { return (recordExists ? SaveResult.RecordUpdated : SaveResult.RecordInserted); }
            }

            //SAVE IS SUCCESSFUL IF OBJECT IS NOT DIRTY
            return SaveResult.NotDirty;
        }

        /// <summary>
        /// Saves that child objects associated with this Vendor object.
        /// </summary>
        public virtual void SaveChildren()
        {
            this.EnsureChildProperties();
            if (this.ProductsLoaded) this.Products.Save();
            if (this.VendorGroupsLoaded) this.VendorGroups.Save();
        }

     }
}
