//Generated by DataSourceBaseGenerator

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Text;
using CommerceBuilder.Common;
using CommerceBuilder.Data;
using CommerceBuilder.Utility;

namespace CommerceBuilder.Personalization
{
    /// <summary>
    /// DataSource class for SharedPersonalization objects
    /// </summary>
    public partial class SharedPersonalizationDataSource
    {
        /// <summary>
        /// Deletes a SharedPersonalization object from the database
        /// </summary>
        /// <param name="sharedPersonalization">The SharedPersonalization object to delete</param>
        /// <returns><b>true</b> if delete operation is successful, <b>false</b> otherwise</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Delete)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static bool Delete(SharedPersonalization sharedPersonalization)
        {
            return sharedPersonalization.Delete();
        }

        /// <summary>
        /// Deletes a SharedPersonalization object with given id from the database
        /// </summary>
        /// <param name="personalizationPathId">Value of PersonalizationPathId of the object to delete.</param>
        /// <returns><b>true</b> if delete operation is successful, <b>false</b> otherwise</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Delete)]
        public static bool Delete(Int32 personalizationPathId)
        {
            SharedPersonalization sharedPersonalization = new SharedPersonalization();
            if (sharedPersonalization.Load(personalizationPathId)) return sharedPersonalization.Delete();
            return false;
        }

        /// <summary>
        /// Inserts/Saves a SharedPersonalization object to the database.
        /// </summary>
        /// <param name="sharedPersonalization">The SharedPersonalization object to insert</param>
        /// <returns><b>SaveResult</b> enumeration that represents the result of the save operation.</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Insert)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static SaveResult Insert(SharedPersonalization sharedPersonalization) { return sharedPersonalization.Save(); }

        /// <summary>
        /// Loads a SharedPersonalization object for given Id from the database.
        /// </summary>
        /// <param name="personalizationPathId">Value of PersonalizationPathId of the object to load.</param>
        /// <returns>If the load is successful the newly loaded SharedPersonalization object is returned. If load fails null is returned.</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static SharedPersonalization Load(Int32 personalizationPathId)
        {
            return SharedPersonalizationDataSource.Load(personalizationPathId, true);
        }

        /// <summary>
        /// Loads a SharedPersonalization object for given Id from the database.
        /// </summary>
        /// <param name="personalizationPathId">Value of PersonalizationPathId of the object to load.</param>
        /// <param name="useCache">If true tries to load object from cache first.</param>
        /// <returns>If the load is successful the newly loaded SharedPersonalization object is returned. If load fails null is returned.</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static SharedPersonalization Load(Int32 personalizationPathId, bool useCache)
        {
            if (personalizationPathId == 0) return null;
            SharedPersonalization sharedPersonalization = null;
            string key = "SharedPersonalization_" + personalizationPathId.ToString();
            if (useCache)
            {
                sharedPersonalization = ContextCache.GetObject(key) as SharedPersonalization;
                if (sharedPersonalization != null) return sharedPersonalization;
            }
            sharedPersonalization = new SharedPersonalization();
            if (sharedPersonalization.Load(personalizationPathId))
            {
                if (useCache) ContextCache.SetObject(key, sharedPersonalization);
                return sharedPersonalization;
            }
            return null;
        }

        /// <summary>
        /// Counts the number of SharedPersonalization objects in result if retrieved using the given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the SharedPersonalization objects that should be loaded.</param>
        /// <returns>The number of SharedPersonalization objects matching the criteria</returns>
        public static int CountForCriteria(string sqlCriteria)
        {
            Database database = Token.Instance.Database;
            string whereClause = string.IsNullOrEmpty(sqlCriteria) ? string.Empty : " WHERE " + sqlCriteria;
            DbCommand selectCommand = database.GetSqlStringCommand("SELECT COUNT(*) AS TotalRecords FROM ac_SharedPersonalization" + whereClause);
            return CommerceBuilder.Utility.AlwaysConvert.ToInt(database.ExecuteScalar(selectCommand));
        }

        /// <summary>
        /// Loads a collection of SharedPersonalization objects from the database based on given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the objects that should be loaded.</param>
        /// <returns>A collection of SharedPersonalization objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static SharedPersonalizationCollection LoadForCriteria(string sqlCriteria)
        {
            return LoadForCriteria(sqlCriteria, 0, 0, string.Empty);
        }

        /// <summary>
        /// Loads a collection of SharedPersonalization objects from the database based on given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the objects that should be loaded.</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of SharedPersonalization objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static SharedPersonalizationCollection LoadForCriteria(string sqlCriteria, string sortExpression)
        {
            return LoadForCriteria(sqlCriteria, 0, 0, sortExpression);
        }

        /// <summary>
        /// Loads a collection of SharedPersonalization objects from the database based on given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the objects that should be loaded.</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <returns>A collection of SharedPersonalization objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static SharedPersonalizationCollection LoadForCriteria(string sqlCriteria, int maximumRows, int startRowIndex)
        {
            return LoadForCriteria(sqlCriteria, maximumRows, startRowIndex, string.Empty);
        }

        /// <summary>
        /// Loads a collection of SharedPersonalization objects from the database based on given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the objects that should be loaded.</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of SharedPersonalization objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static SharedPersonalizationCollection  LoadForCriteria(string sqlCriteria, int maximumRows, int startRowIndex, string sortExpression)
        {
            //CREATE THE DYNAMIC SQL TO LOAD OBJECT
            StringBuilder selectQuery = new StringBuilder();
            selectQuery.Append("SELECT");
            if (maximumRows > 0) selectQuery.Append(" TOP " + (startRowIndex + maximumRows).ToString());
            selectQuery.Append(" " + SharedPersonalization.GetColumnNames(string.Empty));
            selectQuery.Append(" FROM ac_SharedPersonalization");
            string whereClause = string.IsNullOrEmpty(sqlCriteria) ? string.Empty : " WHERE " + sqlCriteria;
            selectQuery.Append(whereClause);
            if (!string.IsNullOrEmpty(sortExpression)) selectQuery.Append(" ORDER BY " + sortExpression);
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand(selectQuery.ToString());
            //EXECUTE THE COMMAND
            SharedPersonalizationCollection results = new SharedPersonalizationCollection();
            int thisIndex = 0;
            int rowCount = 0;
            using (IDataReader dr = database.ExecuteReader(selectCommand))
            {
                while (dr.Read() && ((maximumRows < 1) || (rowCount < maximumRows)))
                {
                    if (thisIndex >= startRowIndex)
                    {
                        SharedPersonalization sharedPersonalization = new SharedPersonalization();
                        SharedPersonalization.LoadDataReader(sharedPersonalization, dr);
                        results.Add(sharedPersonalization);
                        rowCount++;
                    }
                    thisIndex++;
                }
                dr.Close();
            }
            return results;
        }

        /// <summary>
        /// Updates/Saves the given SharedPersonalization object to the database.
        /// </summary>
        /// <param name="sharedPersonalization">The SharedPersonalization object to update/save to database.</param>
        /// <returns><b>SaveResult</b> enumeration that represents the result of the save operation.</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Update)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static SaveResult Update(SharedPersonalization sharedPersonalization) { return sharedPersonalization.Save(); }

    }
}
