//Generated by PersistableBaseGenerator

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Text;
using CommerceBuilder.Common;
using CommerceBuilder.Data;
using CommerceBuilder.Shipping;
using CommerceBuilder.Utility;

namespace CommerceBuilder.Shipping
{
    /// <summary>
    /// This class represents a ShipZoneProvince object in the database.
    /// </summary>
    public partial class ShipZoneProvince : IPersistable
    {

#region Constructors

        /// <summary>
        /// Default Constructor
        /// </summary>
        public ShipZoneProvince() { }

        /// <summary>
        /// Constructor with primary key
        /// <param name="shipZoneId">Value of ShipZoneId.</param>
        /// <param name="provinceId">Value of ProvinceId.</param>
        /// </summary>
        public ShipZoneProvince(Int32 shipZoneId, Int32 provinceId)
        {
            this.ShipZoneId = shipZoneId;
            this.ProvinceId = provinceId;
        }

        /// <summary>
        /// Returns a coma separated list of column names in this database object.
        /// </summary>
        /// <param name="prefix">Prefix to use with column names. Leave null or empty for no prefix.</param>
        /// <returns>A coman separated list of column names for this database object.</returns>
        public static string GetColumnNames(string prefix)
        {
          if (string.IsNullOrEmpty(prefix)) prefix = string.Empty;
          else prefix = prefix + ".";
          List<string> columnNames = new List<string>();
          columnNames.Add(prefix + "ShipZoneId");
          columnNames.Add(prefix + "ProvinceId");
          return string.Join(",", columnNames.ToArray());
        }

        /// <summary>
        /// Loads the given ShipZoneProvince object from the given database data reader.
        /// </summary>
        /// <param name="shipZoneProvince">The ShipZoneProvince object to load.</param>
        /// <param name="dr">The database data reader to read data from.</param>
        public static void LoadDataReader(ShipZoneProvince shipZoneProvince, IDataReader dr)
        {
            //SET FIELDS FROM ROW DATA
            shipZoneProvince.ShipZoneId = dr.GetInt32(0);
            shipZoneProvince.ProvinceId = dr.GetInt32(1);
            shipZoneProvince.IsDirty = false;
        }

#endregion

        private Int32 _ShipZoneId;
        private Int32 _ProvinceId;
        private bool _IsDirty;

        /// <summary>
        /// ShipZoneId
        /// </summary>
        [DataObjectField(true, false, false)]
        public Int32 ShipZoneId
        {
            get { return this._ShipZoneId; }
            set
            {
                if (this._ShipZoneId != value)
                {
                    this._ShipZoneId = value;
                    this.IsDirty = true;
                    this._ShipZone = null;
                }
            }
        }

        /// <summary>
        /// ProvinceId
        /// </summary>
        [DataObjectField(true, false, false)]
        public Int32 ProvinceId
        {
            get { return this._ProvinceId; }
            set
            {
                if (this._ProvinceId != value)
                {
                    this._ProvinceId = value;
                    this.IsDirty = true;
                    this._Province = null;
                }
            }
        }

        /// <summary>
        /// Indicates whether this ShipZoneProvince object has changed since it was loaded from the database.
        /// </summary>
        public bool IsDirty
        {
            get { return this._IsDirty; }
            set { this._IsDirty = value; }
        }

#region Parents
        private Province _Province;
        private ShipZone _ShipZone;

        /// <summary>
        /// The Province object that this ShipZoneProvince object is associated with
        /// </summary>
        public Province Province
        {
            get
            {
                if (!this.ProvinceLoaded)
                {
                    this._Province = ProvinceDataSource.Load(this.ProvinceId);
                }
                return this._Province;
            }
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal bool ProvinceLoaded { get { return ((this._Province != null) && (this._Province.ProvinceId == this.ProvinceId)); } }

        /// <summary>
        /// The ShipZone object that this ShipZoneProvince object is associated with
        /// </summary>
        public ShipZone ShipZone
        {
            get
            {
                if (!this.ShipZoneLoaded)
                {
                    this._ShipZone = ShipZoneDataSource.Load(this.ShipZoneId);
                }
                return this._ShipZone;
            }
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal bool ShipZoneLoaded { get { return ((this._ShipZone != null) && (this._ShipZone.ShipZoneId == this.ShipZoneId)); } }

#endregion

        /// <summary>
        /// Deletes this ShipZoneProvince object from the database.
        /// </summary>
        /// <returns><b>true</b> if delete successful, <b>false</b> otherwise.</returns>
        public virtual bool Delete()
        {
            int recordsAffected = 0;
            StringBuilder deleteQuery = new StringBuilder();
            deleteQuery.Append("DELETE FROM ac_ShipZoneProvinces");
            deleteQuery.Append(" WHERE ShipZoneId = @ShipZoneId AND ProvinceId = @ProvinceId");
            Database database = Token.Instance.Database;
            using (DbCommand deleteCommand = database.GetSqlStringCommand(deleteQuery.ToString()))
            {
                database.AddInParameter(deleteCommand, "@ShipZoneId", System.Data.DbType.Int32, this.ShipZoneId);
                database.AddInParameter(deleteCommand, "@ProvinceId", System.Data.DbType.Int32, this.ProvinceId);
                recordsAffected = database.ExecuteNonQuery(deleteCommand);
            }
            return (recordsAffected > 0);
        }

        /// <summary>
        /// Load this ShipZoneProvince object from the database for the given primary key.
        /// </summary>
        /// <param name="shipZoneId">Value of ShipZoneId of the object to load.</param>
        /// <param name="provinceId">Value of ProvinceId of the object to load.</param>
        /// <returns><b>true</b> if load is successful, <b>false</b> otherwise</returns>
        public virtual bool Load(Int32 shipZoneId, Int32 provinceId)
        {
            this.ShipZoneId = shipZoneId;
            this.ProvinceId = provinceId;
            this.IsDirty = false;
            return true;
        }

        /// <summary>
        /// Saves this ShipZoneProvince object to the database.
        /// </summary>
        /// <returns><b>SaveResult</b> enumeration that represents the result of the save operation.</returns>
        public virtual SaveResult Save()
        {
            if (this.IsDirty)
            {
                Database database = Token.Instance.Database;
                bool recordExists = true;
                
                //generate key(s) if needed
                if (recordExists) {
                    //verify whether record is already present
                    StringBuilder selectQuery = new StringBuilder();
                    selectQuery.Append("SELECT COUNT(*) As RecordCount FROM ac_ShipZoneProvinces");
                    selectQuery.Append(" WHERE ShipZoneId = @ShipZoneId AND ProvinceId = @ProvinceId");
                    using (DbCommand selectCommand = database.GetSqlStringCommand(selectQuery.ToString()))
                    {
                        database.AddInParameter(selectCommand, "@ShipZoneId", System.Data.DbType.Int32, this.ShipZoneId);
                        database.AddInParameter(selectCommand, "@ProvinceId", System.Data.DbType.Int32, this.ProvinceId);
                        if ((int)database.ExecuteScalar(selectCommand) == 0)
                        {
                            recordExists = false;
                        }
                    }
                }

                if (recordExists)
                {
                    //RECORD ALREADY EXISTS IN DATABASE
                    this.IsDirty = false;
                    return SaveResult.RecordUpdated;
                }
                else
                {
                    //INSERT
                    StringBuilder insertQuery = new StringBuilder();
                    insertQuery.Append("INSERT INTO ac_ShipZoneProvinces (ShipZoneId, ProvinceId)");
                    insertQuery.Append(" VALUES (@ShipZoneId, @ProvinceId)");
                    using (DbCommand insertCommand = database.GetSqlStringCommand(insertQuery.ToString()))
                    {
                        database.AddInParameter(insertCommand, "@ShipZoneId", System.Data.DbType.Int32, this.ShipZoneId);
                        database.AddInParameter(insertCommand, "@ProvinceId", System.Data.DbType.Int32, this.ProvinceId);
                        int recordsAffected = database.ExecuteNonQuery(insertCommand);
                        //OBJECT IS NOT DIRTY IF RECORD WAS INSERTED
                        this.IsDirty = (recordsAffected == 0);
                        if (this.IsDirty) { return SaveResult.Failed; }
                        return SaveResult.RecordInserted;
                    }
                }

            }

            //SAVE IS SUCCESSFUL IF OBJECT IS NOT DIRTY
            return SaveResult.NotDirty;
        }

     }
}
