//Generated by DataSourceBaseGenerator

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Text;
using CommerceBuilder.Common;
using CommerceBuilder.Data;
using CommerceBuilder.Utility;

namespace CommerceBuilder.Shipping
{
    /// <summary>
    /// DataSource class for Warehouse objects
    /// </summary>
    public partial class WarehouseDataSource
    {
        /// <summary>
        /// Deletes a Warehouse object from the database
        /// </summary>
        /// <param name="warehouse">The Warehouse object to delete</param>
        /// <returns><b>true</b> if delete operation is successful, <b>false</b> otherwise</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Delete)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static bool Delete(Warehouse warehouse)
        {
            return warehouse.Delete();
        }

        /// <summary>
        /// Deletes a Warehouse object with given id from the database
        /// </summary>
        /// <param name="warehouseId">Value of WarehouseId of the object to delete.</param>
        /// <returns><b>true</b> if delete operation is successful, <b>false</b> otherwise</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Delete)]
        public static bool Delete(Int32 warehouseId)
        {
            Warehouse warehouse = new Warehouse();
            if (warehouse.Load(warehouseId)) return warehouse.Delete();
            return false;
        }

        /// <summary>
        /// Inserts/Saves a Warehouse object to the database.
        /// </summary>
        /// <param name="warehouse">The Warehouse object to insert</param>
        /// <returns><b>SaveResult</b> enumeration that represents the result of the save operation.</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Insert)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static SaveResult Insert(Warehouse warehouse) { return warehouse.Save(); }

        /// <summary>
        /// Loads a Warehouse object for given Id from the database.
        /// </summary>
        /// <param name="warehouseId">Value of WarehouseId of the object to load.</param>
        /// <returns>If the load is successful the newly loaded Warehouse object is returned. If load fails null is returned.</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static Warehouse Load(Int32 warehouseId)
        {
            return WarehouseDataSource.Load(warehouseId, true);
        }

        /// <summary>
        /// Loads a Warehouse object for given Id from the database.
        /// </summary>
        /// <param name="warehouseId">Value of WarehouseId of the object to load.</param>
        /// <param name="useCache">If true tries to load object from cache first.</param>
        /// <returns>If the load is successful the newly loaded Warehouse object is returned. If load fails null is returned.</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static Warehouse Load(Int32 warehouseId, bool useCache)
        {
            if (warehouseId == 0) return null;
            Warehouse warehouse = null;
            string key = "Warehouse_" + warehouseId.ToString();
            if (useCache)
            {
                warehouse = ContextCache.GetObject(key) as Warehouse;
                if (warehouse != null) return warehouse;
            }
            warehouse = new Warehouse();
            if (warehouse.Load(warehouseId))
            {
                if (useCache) ContextCache.SetObject(key, warehouse);
                return warehouse;
            }
            return null;
        }

        /// <summary>
        /// Counts the number of Warehouse objects in result if retrieved using the given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the Warehouse objects that should be loaded.</param>
        /// <returns>The number of Warehouse objects matching the criteria</returns>
        public static int CountForCriteria(string sqlCriteria)
        {
            Database database = Token.Instance.Database;
            string whereClause = string.IsNullOrEmpty(sqlCriteria) ? string.Empty : " WHERE " + sqlCriteria;
            DbCommand selectCommand = database.GetSqlStringCommand("SELECT COUNT(*) AS TotalRecords FROM ac_Warehouses" + whereClause);
            return CommerceBuilder.Utility.AlwaysConvert.ToInt(database.ExecuteScalar(selectCommand));
        }

        /// <summary>
        /// Loads a collection of Warehouse objects from the database based on given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the objects that should be loaded.</param>
        /// <returns>A collection of Warehouse objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static WarehouseCollection LoadForCriteria(string sqlCriteria)
        {
            return LoadForCriteria(sqlCriteria, 0, 0, string.Empty);
        }

        /// <summary>
        /// Loads a collection of Warehouse objects from the database based on given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the objects that should be loaded.</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of Warehouse objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static WarehouseCollection LoadForCriteria(string sqlCriteria, string sortExpression)
        {
            return LoadForCriteria(sqlCriteria, 0, 0, sortExpression);
        }

        /// <summary>
        /// Loads a collection of Warehouse objects from the database based on given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the objects that should be loaded.</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <returns>A collection of Warehouse objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static WarehouseCollection LoadForCriteria(string sqlCriteria, int maximumRows, int startRowIndex)
        {
            return LoadForCriteria(sqlCriteria, maximumRows, startRowIndex, string.Empty);
        }

        /// <summary>
        /// Loads a collection of Warehouse objects from the database based on given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the objects that should be loaded.</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of Warehouse objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static WarehouseCollection  LoadForCriteria(string sqlCriteria, int maximumRows, int startRowIndex, string sortExpression)
        {
            //CREATE THE DYNAMIC SQL TO LOAD OBJECT
            StringBuilder selectQuery = new StringBuilder();
            selectQuery.Append("SELECT");
            if (maximumRows > 0) selectQuery.Append(" TOP " + (startRowIndex + maximumRows).ToString());
            selectQuery.Append(" " + Warehouse.GetColumnNames(string.Empty));
            selectQuery.Append(" FROM ac_Warehouses");
            string whereClause = string.IsNullOrEmpty(sqlCriteria) ? string.Empty : " WHERE " + sqlCriteria;
            selectQuery.Append(whereClause);
            if (!string.IsNullOrEmpty(sortExpression)) selectQuery.Append(" ORDER BY " + sortExpression);
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand(selectQuery.ToString());
            //EXECUTE THE COMMAND
            WarehouseCollection results = new WarehouseCollection();
            int thisIndex = 0;
            int rowCount = 0;
            using (IDataReader dr = database.ExecuteReader(selectCommand))
            {
                while (dr.Read() && ((maximumRows < 1) || (rowCount < maximumRows)))
                {
                    if (thisIndex >= startRowIndex)
                    {
                        Warehouse warehouse = new Warehouse();
                        Warehouse.LoadDataReader(warehouse, dr);
                        results.Add(warehouse);
                        rowCount++;
                    }
                    thisIndex++;
                }
                dr.Close();
            }
            return results;
        }

        /// <summary>
        /// Counts the number of Warehouse objects associated with the given ShipMethodId
        /// </summary>
        /// <param name="shipMethodId">The given ShipMethodId</param>
        /// <returns>The number of Warehouse objects associated with with the given ShipMethodId</returns>
        public static int CountForShipMethod(Int32 shipMethodId)
        {
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand("SELECT COUNT(*) AS TotalRecords FROM ac_ShipMethodWarehouses WHERE ShipMethodId = @shipMethodId");
            database.AddInParameter(selectCommand, "@shipMethodId", System.Data.DbType.Int32, shipMethodId);
            return CommerceBuilder.Utility.AlwaysConvert.ToInt(database.ExecuteScalar(selectCommand));
        }
        /// <summary>
        /// Loads the Warehouse objects associated with the given ShipMethodId
        /// </summary>
        /// <param name="shipMethodId">The given ShipMethodId</param>
        /// <returns>A collection of Warehouse objects associated with with the given ShipMethodId</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static WarehouseCollection LoadForShipMethod(Int32 shipMethodId)
        {
            return WarehouseDataSource.LoadForShipMethod(shipMethodId, 0, 0, string.Empty);
        }
        /// <summary>
        /// Loads the Warehouse objects associated with the given ShipMethodId
        /// </summary>
        /// <param name="shipMethodId">The given ShipMethodId</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of Warehouse objects associated with with the given ShipMethodId</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static WarehouseCollection LoadForShipMethod(Int32 shipMethodId, string sortExpression)
        {
            return WarehouseDataSource.LoadForShipMethod(shipMethodId, 0, 0, sortExpression);
        }
        /// <summary>
        /// Loads the Warehouse objects associated with the given ShipMethodId
        /// </summary>
        /// <param name="shipMethodId">The given ShipMethodId</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <returns>A collection of Warehouse objects associated with with the given ShipMethodId</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static WarehouseCollection LoadForShipMethod(Int32 shipMethodId, int maximumRows, int startRowIndex)
        {
            return WarehouseDataSource.LoadForShipMethod(shipMethodId, maximumRows, startRowIndex, string.Empty);
        }
        /// <summary>
        /// Loads the Warehouse objects associated with the given ShipMethodId
        /// </summary>
        /// <param name="shipMethodId">The given ShipMethodId</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of Warehouse objects associated with with the given ShipMethodId</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static WarehouseCollection LoadForShipMethod(Int32 shipMethodId, int maximumRows, int startRowIndex, string sortExpression)
        {
            //CREATE THE DYNAMIC SQL TO LOAD OBJECT
            StringBuilder selectQuery = new StringBuilder();
            selectQuery.Append("SELECT");
            if (maximumRows > 0) selectQuery.Append(" TOP " + (startRowIndex + maximumRows).ToString());
            selectQuery.Append(" " + Warehouse.GetColumnNames("ac_Warehouses"));
            selectQuery.Append(" FROM ac_Warehouses, ac_ShipMethodWarehouses");
            selectQuery.Append(" WHERE ac_Warehouses.WarehouseId = ac_ShipMethodWarehouses.WarehouseId");
            selectQuery.Append(" AND ac_ShipMethodWarehouses.ShipMethodId = @shipMethodId");
            selectQuery.Append(" AND StoreId = @storeId");
            if (!string.IsNullOrEmpty(sortExpression)) selectQuery.Append(" ORDER BY " + sortExpression);
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand(selectQuery.ToString());
            database.AddInParameter(selectCommand, "@shipMethodId", System.Data.DbType.Int32, shipMethodId);
            database.AddInParameter(selectCommand, "@storeId", System.Data.DbType.Int32, Token.Instance.StoreId);
            //EXECUTE THE COMMAND
            WarehouseCollection results = new WarehouseCollection();
            int thisIndex = 0;
            int rowCount = 0;
            using (IDataReader dr = database.ExecuteReader(selectCommand))
            {
                while (dr.Read() && ((maximumRows < 1) || (rowCount < maximumRows)))
                {
                    if (thisIndex >= startRowIndex)
                    {
                        Warehouse warehouse = new Warehouse();
                        Warehouse.LoadDataReader(warehouse, dr);
                        results.Add(warehouse);
                        rowCount++;
                    }
                    thisIndex++;
                }
                dr.Close();
            }
            return results;
        }

        /// <summary>
        /// Counts the number of Warehouse objects for the given CountryCode in the database.
        /// <param name="countryCode">The given CountryCode</param>
        /// </summary>
        /// <returns>The Number of Warehouse objects for the given CountryCode in the database.</returns>
        public static int CountForCountry(String countryCode)
        {
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand("SELECT COUNT(*) AS TotalRecords FROM ac_Warehouses WHERE CountryCode = @countryCode");
            database.AddInParameter(selectCommand, "@countryCode", System.Data.DbType.String, NullableData.DbNullify(countryCode));
            return CommerceBuilder.Utility.AlwaysConvert.ToInt(database.ExecuteScalar(selectCommand));
        }

        /// <summary>
        /// Loads a collection of Warehouse objects for the given CountryCode from the database
        /// </summary>
        /// <param name="countryCode">The given CountryCode</param>
        /// <returns>A collection of Warehouse objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static WarehouseCollection LoadForCountry(String countryCode)
        {
            return LoadForCountry(countryCode, 0, 0, string.Empty);
        }

        /// <summary>
        /// Loads a collection of Warehouse objects for the given CountryCode from the database
        /// </summary>
        /// <param name="countryCode">The given CountryCode</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of Warehouse objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static WarehouseCollection LoadForCountry(String countryCode, string sortExpression)
        {
            return LoadForCountry(countryCode, 0, 0, sortExpression);
        }

        /// <summary>
        /// Loads a collection of Warehouse objects for the given CountryCode from the database
        /// </summary>
        /// <param name="countryCode">The given CountryCode</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <returns>A collection of Warehouse objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static WarehouseCollection LoadForCountry(String countryCode, int maximumRows, int startRowIndex)
        {
            return LoadForCountry(countryCode, maximumRows, startRowIndex, string.Empty);
        }

        /// <summary>
        /// Loads a collection of Warehouse objects for the given CountryCode from the database
        /// </summary>
        /// <param name="countryCode">The given CountryCode</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of Warehouse objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static WarehouseCollection LoadForCountry(String countryCode, int maximumRows, int startRowIndex, string sortExpression)
        {
            //CREATE THE DYNAMIC SQL TO LOAD OBJECT
            StringBuilder selectQuery = new StringBuilder();
            selectQuery.Append("SELECT");
            if (maximumRows > 0) selectQuery.Append(" TOP " + (startRowIndex + maximumRows).ToString());
            selectQuery.Append(" " + Warehouse.GetColumnNames(string.Empty));
            selectQuery.Append(" FROM ac_Warehouses");
            selectQuery.Append(" WHERE CountryCode = @countryCode");
            if (!string.IsNullOrEmpty(sortExpression)) selectQuery.Append(" ORDER BY " + sortExpression);
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand(selectQuery.ToString());
            database.AddInParameter(selectCommand, "@countryCode", System.Data.DbType.String, NullableData.DbNullify(countryCode));
            //EXECUTE THE COMMAND
            WarehouseCollection results = new WarehouseCollection();
            int thisIndex = 0;
            int rowCount = 0;
            using (IDataReader dr = database.ExecuteReader(selectCommand))
            {
                while (dr.Read() && ((maximumRows < 1) || (rowCount < maximumRows)))
                {
                    if (thisIndex >= startRowIndex)
                    {
                        Warehouse warehouse = new Warehouse();
                        Warehouse.LoadDataReader(warehouse, dr);
                        results.Add(warehouse);
                        rowCount++;
                    }
                    thisIndex++;
                }
                dr.Close();
            }
            return results;
        }

        /// <summary>
        /// Counts the number of Warehouse objects for the current store.
        /// </summary>
        /// <returns>The Number of Warehouse objects in the current store.</returns>
        public static int CountForStore()
        {
            int storeId = Token.Instance.StoreId;
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand("SELECT COUNT(*) AS TotalRecords FROM ac_Warehouses WHERE StoreId = @storeId");
            database.AddInParameter(selectCommand, "@storeId", System.Data.DbType.Int32, storeId);
            return CommerceBuilder.Utility.AlwaysConvert.ToInt(database.ExecuteScalar(selectCommand));
        }

        /// <summary>
        /// Loads a collection of Warehouse objects for the current store from the database
        /// </summary>
        /// <returns>A collection of Warehouse objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static WarehouseCollection LoadForStore()
        {
            return LoadForStore(0, 0, string.Empty);
        }

        /// <summary>
        /// Loads a collection of Warehouse objects for the current store from the database. Sorts using the given sort exrpression.
        /// </summary>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of Warehouse objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static WarehouseCollection LoadForStore(string sortExpression)
        {
            return LoadForStore(0, 0, sortExpression);
        }

        /// <summary>
        /// Loads a collection of Warehouse objects for the current store from the database.
        /// </summary>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <returns>A collection of Warehouse objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static WarehouseCollection LoadForStore(int maximumRows, int startRowIndex)
        {
            return LoadForStore(maximumRows, startRowIndex, string.Empty);
        }

        /// <summary>
        /// Loads a collection of Warehouse objects for the current store from the database. Sorts using the given sort exrpression.
        /// </summary>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of Warehouse objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static WarehouseCollection LoadForStore(int maximumRows, int startRowIndex, string sortExpression)
        {
            int storeId = Token.Instance.StoreId;
            //CREATE THE DYNAMIC SQL TO LOAD OBJECT
            StringBuilder selectQuery = new StringBuilder();
            selectQuery.Append("SELECT");
            if (maximumRows > 0) selectQuery.Append(" TOP " + (startRowIndex + maximumRows).ToString());
            selectQuery.Append(" " + Warehouse.GetColumnNames(string.Empty));
            selectQuery.Append(" FROM ac_Warehouses");
            selectQuery.Append(" WHERE StoreId = @storeId");
            if (!string.IsNullOrEmpty(sortExpression)) selectQuery.Append(" ORDER BY " + sortExpression);
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand(selectQuery.ToString());
            database.AddInParameter(selectCommand, "@storeId", System.Data.DbType.Int32, storeId);
            //EXECUTE THE COMMAND
            WarehouseCollection results = new WarehouseCollection();
            int thisIndex = 0;
            int rowCount = 0;
            using (IDataReader dr = database.ExecuteReader(selectCommand))
            {
                while (dr.Read() && ((maximumRows < 1) || (rowCount < maximumRows)))
                {
                    if (thisIndex >= startRowIndex)
                    {
                        Warehouse warehouse = new Warehouse();
                        Warehouse.LoadDataReader(warehouse, dr);
                        results.Add(warehouse);
                        rowCount++;
                    }
                    thisIndex++;
                }
                dr.Close();
            }
            return results;
        }

        /// <summary>
        /// Updates/Saves the given Warehouse object to the database.
        /// </summary>
        /// <param name="warehouse">The Warehouse object to update/save to database.</param>
        /// <returns><b>SaveResult</b> enumeration that represents the result of the save operation.</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Update)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static SaveResult Update(Warehouse warehouse) { return warehouse.Save(); }

    }
}
